### ISSUE TITLE
Update to Gnome 44

### ISSUE THREAD

**Issue by codingepaduli** [flathub/me.kozec.syncthingtk#113]
Please, update the runtime to org.gnome.Platform/x86_64/44
Thanks

**Comment by davidstrauss** [comment]
I'm working on a patch here: https://github.com/flathub/me.kozec.syncthingtk/pull/137

**Comment by superuser-miguel** [comment]
Info: runtime org.gnome.Platform branch 43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   me.kozec.syncthingtk

Anything I can do to help?

**Comment by muelli** [comment]
yeah, you can either try to get the latest syncthing built with the current runtime or build Go 1.20, e.g. from here https://github.com/flathub/org.freedesktop.Sdk.Extension.golang/blob/branch/21.08/org.freedesktop.Sdk.Extension.golang.yaml for the newer runtime.

**Comment by muelli** [comment]
superseded #150
