### ISSUE TITLE
syncthing-GTK no update check at start-up

### ISSUE THREAD

**Issue by AWHubGit** [flathub/me.kozec.syncthingtk#14]
Each time syncthing-GTK starts it throws:
me.kozec.syncthingtk.desktop[1041]: I App Checking for updates...
me.kozec.syncthingtk.desktop[1041]: I App Warning: No write access to daemon binary; Skipping update check.

me.kozec.syncthingtk was installed from flathub.

https://github.com/clearlinux/distribution/issues/1182

**Comment by TingPing** [comment]
Based on the warning that is entirely expected and how its designed to work.

**Comment by AWHubGit** [comment]
> Based on the warning that is entirely expected and how its designed to work.

Sorry. Do not understand what this means. Does the update fail? Is it done? How to perform an update?
