### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by AWHubGit** [flathub/me.kozec.syncthingtk#19]
Syncthing Core (CLI & Web UI)
Latest is v1.3.1
https://syncthing.net/#
but on dl.flathub.org it is ver v0.9.4.3
Please update

**Comment by jurf** [comment]
Hey, sorry, over the past weeks I have been flat out, I am barely managing school work, so unless I can just bump something and it builds (which, if you look at the PRs, is not the case with Syncthing), I cannot update it now.

I am open to PRs – if they build.
