### ISSUE TITLE
Possible to start daemon at startup?

### ISSUE THREAD

**Issue by A6GibKm** [flathub/me.kozec.syncthingtk#22]
It is possible to automatically start the syncthing daemon at startup?

**Comment by muelli** [comment]
I'd say that https://specifications.freedesktop.org/autostart-spec/0.5/index.html should help you.

**Comment by A6GibKm** [comment]
You are right, I managed to run it with
```conf
[Desktop Entry]
Type=Application
Name=ProtonMail Bridge
Exec=/usr/bin/flatpak run me.kozec.syncthingtk -m
X-GNOME-Autostart-enabled=true
```
But I would rather run syncthing and not syncthing-gtk

**Comment by A6GibKm** [comment]
It is possible to do --command with flags? e.g. `flatpak run --command=syncthing -no-window me.kozec.syncthingtk`.

If not I could PR a wrapper for it. I am closing this for now.

**Comment by muelli** [comment]
I assume `--command` works with arguments:
```
$ flatpak run --command=syncthing  me.kozec.syncthingtk -no-window
flag provided but not defined: -no-window
Usage:
  syncthing [options]
...
```

I'd be fine with a simple to maintain and to debug wrapper if that doesn't work for you, though.

**Comment by TingPing** [comment]
The application can request the autostart permission but thats a bug to report upstream.

**Comment by A6GibKm** [comment]
@muelli that worked, thanks.
