### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by Docmine17** [flathub/me.kozec.syncthingtk#39]
I just installed it and that appeared when I opened

https://ibb.co/sFtwtSG

In terminal
```
pro@Asus:~$ flatpak run me.kozec.syncthingtk
Gtk-Message: 20:39:58.627: Failed to load module "canberra-gtk-module"
I StatusIcon    Using backend StatusIconGTK3 (primary)
Traceback (most recent call last):
  File "/app/lib/python2.7/site-packages/syncthing_gtk/app.py", line 242, in do_command_line
    if self.setup_connection():
  File "/app/lib/python2.7/site-packages/syncthing_gtk/app.py", line 385, in setup_connection
    self.daemon = Daemon()
  File "/app/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 321, in __init__
    self._read_config()
  File "/app/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 337, in _read_config
    raise InvalidConfigurationException("Failed to read daemon configuration: %s" % e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 26: ordinal not in range(128)
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)

(syncthing-gtk:2): Gdk-CRITICAL **: 20:39:58.852: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

Ubuntu 21.04, Flatpak 1.10.2, Nvidia 1050 Ti with Nvidia 460 driver.

**Comment by muelli** [comment]
hm. I'm thought I was seeing it, too:
```
I StatusIcon    Using backend StatusIconGTK3 (primary)
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Traceback (most recent call last):
  File "/app/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 1057, in _connected
    self._connection = self.connect_to_service_finish(results)
Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
```
But it turned out that the daemon was just slow to start.

Your issue looks like this: https://github.com/kozec/syncthing-gtk/issues/569

The stacktrace suggests that it's related to your configuration. Do you mind sharing your configuration minus your credentials?

**Comment by Docmine17** [comment]
> The stacktrace suggests that it's related to your configuration. Do you mind sharing your configuration minus your credentials?
How can I do this?

**Comment by jurf** [comment]
Got this error on a fresh installation too.

**Comment by jurf** [comment]
BTW I managed to work this around by using the Web version for setup, the GTK interface works fine after that. It happened separately on two machines with fresh installs, so for reproduction, I think you can just start with clearing the folder in .var.

**Comment by Aleksanaa** [comment]
> BTW I managed to work this around by using the Web version for setup, the GTK interface works fine after that. It happened separately on two machines with fresh installs, so for reproduction, I think you can just start with clearing the folder in .var.

What do you refer to the web version?The one from the distribution or with flatpak?Which port should I use?

**Comment by jurf** [comment]
I don‘t remember which port, but Syncthing itself locally hosts a webpage, you need to navigate to that.

**Comment by muelli** [comment]
the new version uses python3.
Can you check whether it works better now?

**Comment by Docmine17** [comment]
**It's working now, no blank screens.**
![image](https://user-images.githubusercontent.com/67164552/200431640-088ae4db-b6f9-404b-82c2-48e1337106a8.png)

**Comment by muelli** [comment]
thanks for checking! And thanks for bearing with us. <3
