### ISSUE TITLE
Logs flooding problem ( around ~20 times / seconds) with error "tk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed"

### ISSUE THREAD

**Issue by lakano** [flathub/me.kozec.syncthingtk#89]
Hi !

Thank you a lot for your flatpak of Syncthing-GTK !

Every 30 seconds, I have around 20 times a log about this same error, stressing a lot my logs/ssd.
Is it possible to fix this warning/error, or at least, to only report it one time at start-up time please? 

Thank you a lot !

> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:46:46 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> janv. 24 17:47:04 dev syncthing-gtk[2508]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
>

**Comment by muelli** [comment]
hm. I don't think I'm experiencing this. How would I notice?

It sounds like something to be reported upstream, though.

**Comment by AWHubGit** [comment]
(syncthing-gtk:2): Gtk-CRITICAL **: 07:42:01.848: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(syncthing-gtk:2): Gtk-CRITICAL **: 07:42:01.949: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(syncthing-gtk:2): Gtk-CRITICAL **: 07:42:02.050: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(syncthing-gtk:2): Gtk-CRITICAL **: 07:42:02.151: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(syncthing-gtk:2): Gtk-CRITICAL **: 07:42:02.252: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(syncthing-gtk:2): Gtk-CRITICAL **: 07:42:02.353: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(syncthing-gtk:2): Gtk-CRITICAL **: 07:42:02.454: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(syncthing-gtk:2): Gtk-CRITICAL **: 07:42:02.555: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

Same for me.

**Comment by A6GibKm** [comment]
This is absolutely an issue with the app, unrelated to flathub. Please report upstream.
